### ISSUE TITLE
Use tc instead of iptables to limit speed

### ISSUE THREAD

**Issue by mis2417** [oxplot/bradybound#2]
`tc` is better at this (i think it requires `tc` binary from busybox).
Check this rudimentary script limited to wlan0:

```sh
#!/system/xbin/bash

MODE=$1
re='^[0-9]+$'
LAN="10.0.7.0/24" #or whatever, maybe all 3 private address classes? 

if [ "$MODE" = "status" ]
then
 su -c 'tc -s qdisc ls dev wlan0' 
 exit
elif [ "$MODE" = "clear" ]
then 
 su -c 'tc qdisc del dev wlan0 ingress 2>/dev/null' 
 exit
elif [[ $MODE =~ $re ]] 
then
 ##downlink only
 su -c 'tc qdisc add dev wlan0 handle ffff: ingress' 
 su -c 'tc filter add dev wlan0 parent ffff: protocol ip prio 50 u32 match ip src $LAN police rate 100mbit burst 10m drop flowid :1' 
 su -c "tc filter add dev wlan0 parent ffff: protocol ip prio 50 u32 match ip src 0.0.0.0/0 police rate ${MODE}kbps burst 10k drop flowid :1"
else
 echo "argument error" 
 echo "must be \"status\"/\"clear\", or a number"
 exit 1
fi
exit 0
```

Upload doesn't work either, because android's `tc` is limited, but download scheduling is less laggy.
As a bonus, LAN is set to 100mbit.

**Comment by oxplot** [comment]
what version of android did this work on?

**Comment by mis2417** [comment]
I've tested this on cyanogenmod 11 and 12.1

**Comment by mis2417** [comment]
just a thought. sh script with a combination of OnNetworkChange intent (like smanager, I don't really know anything about android) will allow to enable limiting automatically.

**Comment by mis2417** [comment]
since marshmallow I noticed tc might not be a good idea, since it requires kernel module (I think) to actually limit speed. that module is not compiled into cm13, so tc throws an error. 
(OnNetworkChange is still valid idea though)
